[package]
name = "prediction-market"
version = "1.1.1"
description = "Solana Prediction Market - USDC Migration + Code Quality Polish"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "prediction_market"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed","event-cpi"] }
anchor-spl = { version = "0.32.1", features = ["metadata"] }
